import React from "react";
import type { Metadata } from "next";
import { HeaderMain, FooterMain } from "@/components/layouts";
import AuthProvider from "@/context/authContext";

export const metadata: Metadata = {
  title: "Main Layout",
  description: "Generated by create next app",
};

export default function MainLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <React.Fragment>
      <AuthProvider>
        <HeaderMain />
        {/* {children} */}
        {/* <FooterMain /> */}
      </AuthProvider>
    </React.Fragment>
  );
}
