import React from "react";
import type { Metadata } from "next";
import AuthProvider from "@/context/authContext";

export const metadata: Metadata = {
  title: "Auth Layout",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <React.Fragment>
      <AuthProvider>{children}</AuthProvider>
    </React.Fragment>
  );
}
